Name = input("Enter your name here: ")
Age = int(input ("How old are you?: "))
Favorite_color = input("What is your favorite color?: ")
Favorite_movie = input("What is your favorite Movie?: ")
Mobile_number = int(input ("Mobile Number: "))
Motto_in_life = input("What is you motto in life?: ")